package dev.gouthaman.regimen.sync.di

import javax.inject.Qualifier

/**
 * Qualifies the Google OAuth web client ID used by Credential Manager's Google ID sign-in.
 * The value comes from `R.string.default_web_client_id`, generated by the `google-services`
 * plugin from `google-services.json` - that plugin only runs on `:app`, so the actual
 * `@Provides` lives there. Only the qualifier itself needs to be reachable from `:core:sync`.
 */
@Qualifier
@Retention(AnnotationRetention.BINARY)
annotation class WebClientId
